### ISSUE TITLE
Add an explanation for how to set-up latest version of master on a Norwegian macine

### ISSUE THREAD

**Issue by sunnivin** [sunnivin/rtd-github-pages#2]
Even though the porting of CIME is described in the general [CIME user guide](http://esmci.github.io/cime/versions/master/html/index.html) it is not obvious how these settings are related to our Norwegian cluster. 

I think a repo with correct configuration [files](https://github.com/gunnartl/config_files_sigma2), like made by @gunnartl, would make life easier for a lot of our new team mates.

**Comment by ziu1986** [comment]
It would probably be smart to link the Norwegian cluster-specific XML config files into a .cime folder in your home directory. On centralized user home directories (like at UiO) this would only have to be done once.
