### ISSUE TITLE
The link_dirtree-script is not working even with access to noresm folder

### ISSUE THREAD

**Issue by gunnartl** [sunnivin/rtd-github-pages#5]
link_dirtree is complaining about lacking access also after i was added to the noresm-group.

Ive tried setting the input-path directly in the config-files and setting the path after creating a case with ./xmlchange, both seem to work fine.

**Comment by sunnivin** [comment]
So, the use of the link_dirtree-script sort of goes under the label: prerequisites or need to have before you can get CTSM-running.

**Comment by gunnartl** [comment]
link_dirtree is not needed when using the configfiles from [here](https://github.com/gunnartl/config_files_sigma2). These are used in the now updated tutorial.
